### ISSUE TITLE
[1.16.5] Please remove max ram limit.

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/MemorySettings#1]
I play with 30 gigs of ram (I have 64) and don't want to be pestered every time I run my pack, please remove the max cap, or make it 64 gigs max, or allow us to toggle max off, I can't think of a situation where max ram would ever be useful.

**Comment by someaddons** [comment]
I can increase the configs max setting to a higher, but there is a reason for a max cap which is that depending on java settings you can make GC clearup times/spikes worse when assigning so much. Only newer GC algs(ZGC/Shenandoa) scale better with large memory sizes. So ideally you got a ~2gb headroom above whats actually needed to run the pack, thus the max setting exists.

Btw if you're pestered by the popup it has a button to turn off the notification and won't pop up again

**Comment by someaddons** [comment]
upped limit in 1.9
