### ISSUE TITLE
[Bug]: Mod causes a full client stall on M1 macs (maybe all Macs?)

### ISSUE THREAD

**Issue by Jaymus3** [someaddons/MemorySettings#2]
### Describe the bug you're experiencing

Tried to launch a modpack with this mod installed, and the pack stalled and didn't proceed with launching.

### Reproducability

Launch a modpack with this mod installed, and it will not load on M1 macs.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://mclo.gs/SpKQfYi

**Comment by someaddons** [comment]
Macs with their custom bugged java version... I've spent way too much time trying to fix it, I'll just keep current for the older version

**Comment by Jaymus3** [comment]
I'm running the Azul build of Java, not the built-in copy.
