### ISSUE TITLE
Packmenue  visual error

### ISSUE THREAD

**Issue by bastegk2** [someaddons/MemorySettings#4]
With the new update and new forge version the mod packmenu dont show the custom buttons.

**Comment by someaddons** [comment]
fill out the template.

**Comment by bastegk2** [comment]
You mean the mod  Packmenu or yours ?, the template for packmenue i have done and for your mod. https://media.discordapp.net/attachments/951957148789788785/1114301489993748601/This.PNG?width=1202&height=676 this is the error. And this is a picture of the woring modpack without your mod now -> https://media.discordapp.net/attachments/951957148789788785/1114301967905325056/This2.PNG?width=1202&height=676 but it displays all of your mod. All works fine with your mod. Only it makes packmenu broke. Your version before has work for my modpack (realistic worlds) VR MRWS. But now not, and i dont can use the older version, because forge gets a update.

**Comment by bastegk2** [comment]
I hope this helps more :)

**Comment by someaddons** [comment]
I meant the issue template on this repo, I need much more information, which version of memory settings which version of packmenu which modloader, steps to reproduce, logs with that issue etc

**Comment by bastegk2** [comment]
There are no protocls sorry, i use this version of packmenu https://www.curseforge.com/minecraft/mc-mods/packmenu/files/4050356 and your version the newest one. https://www.curseforge.com/minecraft/mc-mods/memory-settings/files/4561329. I use forge 1.18.2 40.2.9 . the error was caused by that. That you don't do the integration of the menu as a shield, but directly into the vanilla menu of Minecraft :). The variant before that outside of the package would be enough for me. Unfortunately, this is no longer possible with the new forge update. https://www.curseforge.com/minecraft/mc-mods/memory-settings/files/4560913
