### ISSUE TITLE
[Bug]: Visual Error with Packmenue

### ISSUE THREAD

**Issue by bastegk2** [someaddons/MemorySettings#5]
### Describe the bug you're experiencing

Not showing the Pictures of buttons.  a picture of the visual error -> https://media.discordapp.net/attachments/951957148789788785/1114301489993748601/This.PNG?width=1202&height=676 and after telete the memory settings it looks like this https://media.discordapp.net/attachments/951957148789788785/1114301967905325056/This2.PNG?width=1202&height=676. I hope you can get it to work :) Thanks.

### Reproducability

You need this mods -> https://www.curseforge.com/minecraft/mc-mods/packmenu/files/4050356 and your new version :https://www.curseforge.com/minecraft/mc-mods/memory-settings/files/4561329

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge 40.2.9

### Logs

No log file sry.

**Comment by someaddons** [comment]
fixed in 4.4
