### ISSUE TITLE
[Request] Upload to Modrinth

### ISSUE THREAD

**Issue by RandomlyZay** [someaddons/MemorySettings#6]
I really like this mod and I wanted to include it in my modpack, but it's only on Curseforge. Every single mod, resource pack, and shader in my modpack is on Modrinth. I was wondering if you were willing to put your mod on Modrinth as well since this mod is so useful in preventing players from not allocating enough RAM. It would be greatly appreciated if you at least _considered_ this. Thank you!

**Comment by vaporvee** [comment]
@someaddons not even an answer? i mean they have a good monetization program

**Comment by Fyoncle** [comment]
> @someaddons not even an answer? i mean they have a good monetization program

Idk bro, he is the biggest hater of Modrinth ever existed, idk why he does that too.
