### ISSUE TITLE
Question: Does this fix GC issues?

### ISSUE THREAD

**Issue by Lepommejamez** [someaddons/MemorySettings#7]
I found this mod while looking for a fix to my game dropping to 2~ fps every few seconds. I researched and found this is the garbage collector clearing ram and that's what causes it. Does this fix that?

**Comment by Lepommejamez** [comment]
Nevermind, I just tried it out and it does.

**Comment by someaddons** [comment]
No this is just for telling people to assign a fitting amount of memory. It can indirectly solve GC issues since those might be caused by incorrect amounts of memory used
